# Generated by Django 5.0.2 on 2024-03-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the loan status.",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A detailed description of the loan status.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "allow_auto_calculations",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether automatic calculations are allowed for this loan status.",
                        verbose_name="Allow Auto Calculations",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether this loan status is active.",
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Status",
                "verbose_name_plural": "Loan Statuses",
            },
        ),
    ]
