# Generated by Django 5.0.6 on 2024-06-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_product", "0003_groupproduct_allow_half_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupproduct",
            name="grace_period_days",
            field=models.IntegerField(default=0, verbose_name="grace period in days"),
        ),
    ]
