# Generated by Django 5.0.2 on 2024-03-07 23:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "loan_approval_required",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if loans require approval before disbursement for this branch.",
                    ),
                ),
                (
                    "loan_application_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if loan applications are allowed for this branch.",
                    ),
                ),
                (
                    "min_loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum loan amount applicable for this branch.",
                        max_digits=15,
                    ),
                ),
                (
                    "max_loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum loan amount applicable for this branch.",
                        max_digits=15,
                    ),
                ),
                (
                    "default_interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default interest rate for loans for this branch.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Setting",
                "verbose_name_plural": "Branch Settings",
            },
        ),
    ]
