# Generated by Django 5.0.2 on 2024-03-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company_name",
                    models.CharField(
                        help_text="The name of the company using the loan management system.",
                        max_length=255,
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        help_text="The company logo.",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Primary contact email for the company.",
                        max_length=254,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        help_text="Primary contact phone number for the company.",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(help_text="Company's physical address.")),
                (
                    "default_interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default global interest rate for loans.",
                        max_digits=5,
                    ),
                ),
                (
                    "min_loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum loan amount applicable globally.",
                        max_digits=15,
                    ),
                ),
                (
                    "max_loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum loan amount applicable globally.",
                        max_digits=15,
                    ),
                ),
                (
                    "loan_approval_required",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if loans require approval before disbursement globally.",
                    ),
                ),
                (
                    "loan_application_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if loan applications are allowed globally.",
                    ),
                ),
                (
                    "fiscal_year_start",
                    models.DateField(help_text="Start date of the fiscal year."),
                ),
                (
                    "fiscal_year_end",
                    models.DateField(help_text="End date of the fiscal year."),
                ),
                (
                    "currency_code",
                    models.CharField(
                        default="USD",
                        help_text="Default currency code for financial transactions.",
                        max_length=3,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="The default timezone for the system operations.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Setting",
                "verbose_name_plural": "Global Settings",
            },
        ),
    ]
