# Generated by Django 5.0.2 on 2024-03-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the payment gateway.",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the payment gateway.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        help_text="Type of the payment gateway (Online/Offline).",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "is_disbursement",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the gateway is used for disbursements.",
                        verbose_name="Is Disbursement",
                    ),
                ),
                (
                    "is_repayment",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the gateway is used for repayments.",
                        verbose_name="Is Repayment",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the payment gateway is active.",
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Gateway",
                "verbose_name_plural": "Payment Gateways",
            },
        ),
    ]
