# Generated by Django 5.0.2 on 2024-03-07 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branch_products", "0002_initial"),
        ("branches", "0001_initial"),
        ("clients", "0005_alter_clientlimit_client"),
        ("currencies", "0001_initial"),
        ("group_product", "0002_initial"),
        ("loan_applications", "0002_alter_loanapplication_options_and_more"),
        ("loan_statuses", "0002_loanstatus_created_at_loanstatus_deleted_at_and_more"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The total amount of the loan.",
                        max_digits=15,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The interest rate of the loan.",
                        max_digits=10,
                        verbose_name="Interest Rate",
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The total amount of interest applied to the loan.",
                        max_digits=15,
                        verbose_name="Interest Amount",
                    ),
                ),
                (
                    "disbursement_date",
                    models.DateTimeField(
                        help_text="The date and time when the loan was disbursed.",
                        verbose_name="Disbursement Date",
                    ),
                ),
                (
                    "repayment_date",
                    models.DateTimeField(
                        help_text="The expected date and time for the loan to be fully repaid.",
                        verbose_name="Repayment Date",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff member who approved this loan. Null if not yet approved.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_loans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="The branch through which the loan was issued.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_loans",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "branch_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="The branch product associated with this loan.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="branch_products.branchproduct",
                        verbose_name="Branch Product",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client to whom the loan is issued.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The staff member who created this loan record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_loans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="The currency in which the loan is issued.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currencies.currency",
                        verbose_name="Currency",
                    ),
                ),
                (
                    "group_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="The group product associated with this loan.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="group_product.groupproduct",
                        verbose_name="Group Product",
                    ),
                ),
                (
                    "loan_application",
                    models.ForeignKey(
                        blank=True,
                        help_text="The loan application associated with this loan.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loan_applications.loanapplication",
                        verbose_name="Loan Application",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="The loan product associated with this loan.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="The current status of the loan.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loan_statuses.loanstatus",
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
            },
        ),
    ]
