# Generated by Django 5.0.2 on 2024-03-08 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="repayment_date",
            new_name="expected_repayment_date",
        ),
        migrations.AddField(
            model_name="loan",
            name="next_due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the next payment is due.",
                null=True,
                verbose_name="Next Due Date",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date and time when the loan period start",
                verbose_name="Start Date",
            ),
            preserve_default=False,
        ),
    ]
