# Generated by Django 5.0.2 on 2024-03-14 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_statuses", "0002_loanstatus_created_at_loanstatus_deleted_at_and_more"),
        ("loans", "0003_remove_loan_product_alter_loan_interest_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.ForeignKey(
                default=11,
                help_text="The current status of the loan.",
                on_delete=django.db.models.deletion.CASCADE,
                to="loan_statuses.loanstatus",
                verbose_name="Status",
            ),
        ),
    ]
