# Generated by Django 5.0.6 on 2024-06-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_alter_loan_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="status",
        ),
    ]
