# Generated by Django 5.0.6 on 2024-06-04 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_statuses", "0002_loanstatus_created_at_loanstatus_deleted_at_and_more"),
        ("loans", "0005_remove_loan_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="status",
            field=models.ForeignKey(
                default=1,
                help_text="The current status of the loan.",
                on_delete=django.db.models.deletion.CASCADE,
                to="loan_statuses.loanstatus",
                verbose_name="Status",
            ),
        ),
    ]
