# Generated by Django 5.0.2 on 2024-03-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interest",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="interest rate (%)",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="maximum loan amount",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="minimum loan amount",
                    ),
                ),
                ("min_period", models.IntegerField(verbose_name="minimum period")),
                ("max_period", models.IntegerField(verbose_name="maximum period")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                        verbose_name="branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "branch product",
                "verbose_name_plural": "branch products",
            },
        ),
    ]
