# Generated by Django 5.0.2 on 2024-03-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_products", "0003_branchproduct_allow_half_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchproduct",
            name="grace_period_days",
            field=models.IntegerField(default=0, verbose_name="grace period in days"),
        ),
    ]
