# Generated by Django 5.0.2 on 2024-03-06 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("charges", "0001_initial"),
        ("group_product", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProductCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charges.charge",
                        verbose_name="Charge",
                    ),
                ),
                (
                    "group_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group_product.groupproduct",
                        verbose_name="Group Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Product Charge",
                "verbose_name_plural": "Group Product Charges",
            },
        ),
    ]
