# Generated by Django 5.0.2 on 2024-03-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="next_of_kin",
        ),
        migrations.AddField(
            model_name="nextofkin",
            name="client",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_of_kin",
                to="clients.client",
                verbose_name="Client",
            ),
            preserve_default=False,
        ),
    ]
