# Generated by Django 5.0.2 on 2024-03-05 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_remove_client_next_of_kin_nextofkin_client"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("max_loan", models.DecimalField(decimal_places=2, max_digits=15)),
                ("credit_score", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-last_modified"],
                "abstract": False,
            },
        ),
    ]
