# Generated by Django 5.0.2 on 2024-03-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("model_name", models.CharField(max_length=100)),
                ("record_id", models.IntegerField()),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True, default=None, null=True)),
                ("new_value", models.TextField(blank=True, default=None, null=True)),
                ("action", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["-created_at", "-last_modified"],
                "abstract": False,
            },
        ),
    ]
