# Generated by Django 5.0.2 on 2024-03-06 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loan_statuses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Amount"
                    ),
                ),
                (
                    "amount_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("percentage", "Percentage")],
                        max_length=20,
                        verbose_name="Amount Type",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=20,
                        verbose_name="Charge Type",
                    ),
                ),
                (
                    "charge_application",
                    models.CharField(
                        choices=[
                            ("principal", "Principal"),
                            ("balance", "Balance"),
                            ("other", "Other"),
                        ],
                        default="principal",
                        max_length=20,
                        verbose_name="Charge Application",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("one-time", "One-time"), ("recurring", "Recurring")],
                        max_length=20,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto", "Auto")],
                        max_length=20,
                        verbose_name="Mode",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "loan_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charges",
                        to="loan_statuses.loanstatus",
                        verbose_name="Loan Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charge",
                "verbose_name_plural": "Charges",
            },
        ),
    ]
