# Generated by Django 5.0.2 on 2024-03-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charges", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charge",
            name="frequency",
        ),
    ]
