# Generated by Django 5.0.2 on 2024-03-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loanapplication",
            options={
                "verbose_name": "Loan Application",
                "verbose_name_plural": "Loan Applications",
            },
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current status of the loan application.",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
